---
# -------------------------------------------------------------------------
# To Do: Implement your workload deployment tasks here
# -------------------------------------------------------------------------

- name: Example workload, print example variable values
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop:
  - "Variable 1: {{ ocp4_workload_operate_models_rhoai_variable_1 }}"
  - "Variable 2: {{ ocp4_workload_operate_models_rhoai_variable_2 }}"

- name: The following variables are always available
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop:
  - "openshift_console_url:                 {{ openshift_console_url }}"
  - "openshift_api_url:                     {{ openshift_api_url }}"
  - "openshift_cluster_ingress_domain:      {{ openshift_cluster_ingress_domain }}"
