---
name: Static Checks Pull Request

on:
  pull_request:
    branches:
    - main

jobs:
  static-checks:
    name: Run static tests using tox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.12'

    steps:
    - name: Get Repository Code
      id: get_repo_code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run static checks
      run: |
        pip install tox
        tox -c tests/static -- ${{ github.base_ref }} ${{ github.sha }}

  all_checks_complete:
    needs: [static-checks]
    runs-on: ubuntu-latest
    steps:
    - run: echo "All checks passed!"
...